# Server 配置
server:
  port: 8080

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jim.ssr.mybatis.entity


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.133.229.103:13306/ssr2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root