# Server 配置
server:
  port: 14156

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jim.ssr.mybatis.entity


spring:
  datasource:
    url: jdbc:h2:file:~/.config/ByteTicker/db/h2db #;IFEXISTS=FALSE # Ubuntu
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    path: ~/.config/ByteTicker/logs
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://101.133.229.103:13306/ssr2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: root
